apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: rhcl-demo-lab
  labels:
    app: orders
    service: orders
    version: v1
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: rhcl-demo-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: "quay.io/rh-ee-egevorky/rhcl/orders:0.1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: KEYCLOAK_ISSUER
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: KEYCLOAK_CLIENT_ID
            - name: ORDERS_READ_ROLE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: ORDERS_READ_ROLE
            - name: ORDERS_WRITE_ROLE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: ORDERS_WRITE_ROLE
            - name: ORDERS_DELETE_ROLE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: ORDERS_DELETE_ROLE
            - name: ORDERS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: ORDERS_DB_URL
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
