apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: lan-auth-advanced
  namespace: rhcl-demo-lab
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: rhcl-demo-lab
    namespace: rhcl-demo-lab
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      authentication:
        - name: keycloak
          jwt:
            issuer: https://auth.arencloud.com:30238/realms/rhcl-demo
            remoteJWKS:
              uri: https://auth.arencloud.com:30238/realms/rhcl-demo/protocol/openid-connect/certs
            audiences:
              - rhcl-microservices
      authorization:
        - name: realm-roles-and-headers
          opa:
            inlineRego: |
              package kuadrant.authz
              default allow = false
              roles := input.auth.identity.realm_access.roles
              path := input.context.request.http.path
              method := upper(input.context.request.http.method)
              headers := input.context.request.http.headers
              tenant := input.context.request.http.query["tenant"][0]
              body := input.context.request.http.body

              # Require LAN marker header and tenant param
              required_header {
                lower(headers["x-env"][0]) == "lan"
              }
              required_tenant {
                tenant == "demo"
              }

              allow {
                required_header
                required_tenant
                startswith(path, "/api/v1/items")
                method == "GET"
                roles[_] == "inventory.reader"
              }
              allow {
                required_header
                required_tenant
                startswith(path, "/api/v1/items")
                method != "GET"
                roles[_] == "inventory.writer"
              }
              allow {
                required_header
                required_tenant
                startswith(path, "/api/v1/orders")
                method == "GET"
                roles[_] == "orders.reader"
              }
              allow {
                required_header
                required_tenant
                startswith(path, "/api/v1/orders")
                method != "GET"
                roles[_] == "orders.writer"
                body.tenant == "demo"
              }