apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forward-custom-header-x-env
  namespace: app-global-dmz
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.http.ext_authz"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            include_headers_in_check:
              - x-env