apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: dmz-auth-inventory-policy
  namespace: app-global-dmz
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: inventory-route
    namespace: app-global-dmz
  rules:
    matches:
      - path:
          type: PathPrefix
          value: /
    authentication:
      keycloak:
        jwt:
          issuerUrl: https://auth.arencloud.com:30238/realms/rhcl-demo
          #jwksUrl: https://auth.arencloud.com:30238/realms/rhcl-demo/protocol/openid-connect/certs
          audiences:
            - rhcl-microservices
    authorization:
      opa-role-checks:
        opa:
          rego: |
            package kuadrant.authz
                  
            ####################################################################
            # Basic request context
            ####################################################################
            roles := input.auth.identity.realm_access.roles
            path := input.context.request.http.path
            method := upper(input.context.request.http.method)
            headers := input.context.request.http.headers
            
            ####################################################################
            # RELIABLE extraction of "x-env" header regardless of normalization
            ####################################################################
            xenv := lower(headers["x-env"])
            xenv_val := xenv else ""

            ####################################################################
            # Required header logic
            ####################################################################
            required_header := xenv_val == "dmz"

            ####################################################################
            # Authorization rules
            ####################################################################
            allow {
              startswith(path, "/api/v1/items")
              method == "GET"
              roles[_] == "inventory.reader"
            }
            allow {
              required_header
              startswith(path, "/api/v1/items")
              method == "POST"
              roles[_] == "inventory.writer"
            }
            allow {
              required_header
              startswith(path, "/api/v1/items")
              method == "PUT"
              roles[_] == "inventory.writer"
            }
            allow {
              required_header
              startswith(path, "/api/v1/items")
              method == "DELETE"
              roles[_] == "inventory.deleter"
            }
            
            ####################################################################
            # Debug output
            # Returned ONLY when "allow" is true
            ####################################################################
            response := {
              "headers": {
                "X-Debug-Xenv": xenv_val,
                "X-Debug-All-Headers": json.marshal(headers),
                "X-Debug-Required-Header": required_header,
                "X-Debug-Path": path,
                "X-Debug-Method": method
              }
            } {
              allow
            }