apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: dmz-auth-inventory-policy
  namespace: app-global-dmz
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: inventory-route
    namespace: app-global-dmz
  rules:
    matches:
      - path:
          type: PathPrefix
          value: /
    authentication:
      keycloak:
        jwt:
          issuerUrl: https://auth.arencloud.com:30238/realms/rhcl-demo
          #jwksUrl: https://auth.arencloud.com:30238/realms/rhcl-demo/protocol/openid-connect/certs
          audiences:
            - rhcl-microservices
    authorization:
      opa-role-checks:
        opa:
          rego: |
            package kuadrant.authz
            roles := input.auth.identity.realm_access.roles
            path := input.context.request.http.path
            method := upper(input.context.request.http.method)
            headers := input.context.request.headers
            
            # Safely read header (avoids crash if missing)
            xenv_val := "" {
              input.context.request.headers["x-env"]
              xenv_val := lower(input.context.request.headers["x-env"])
            } else {
              xenv_val := ""
            }
            allow = true
            
            # The 'output' is captured regardless of the 'allow' decision
            # (though only useful if 'allow' is true for the response headers)
            output := {
              "xenv_debug_value": xenv_val
            }
            
            #required_header {
            #  xenv == "dmz"
            #}
            #
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "GET"
            #  roles[_] == "inventory.reader"
            #}
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "POST"
            #  roles[_] == "inventory.writer"
            #}
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "PUT"
            #  roles[_] == "inventory.writer"
            #}
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "DELETE"
            #  roles[_] == "inventory.deleter"
            #}
            
            # -----------------------------
            # DEBUG OUTPUT (Based on the OPA output)
            # -----------------------------
            response := {
              "headers": {
                # This uses the OPA output from the 'output' rule below
                "X-Debug-Xenv-Value": "{auth.authorization.opa-role-checks.output.xenv_debug_value}",
                "X-Debug-Path": path,
                "X-Debug-Method": method,
              }
            }