apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: dmz-auth-inventory-policy
  namespace: app-global-dmz
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: inventory-route
    namespace: app-global-dmz
  rules:
    matches:
      - path:
          type: PathPrefix
          value: /
    authentication:
      keycloak:
        jwt:
          issuerUrl: https://auth.arencloud.com:30238/realms/rhcl-demo
          audiences:
            - rhcl-microservices
    authorization:
      opa-role-checks:
        opa:
          rego: |
            package kuadrant.authz
                  
            ####################################################################
            # Basic request context
            ####################################################################
            roles := input.auth.identity.realm_access.roles
            path := input.context.request.http.path
            method := upper(input.context.request.http.method)
            headers := input.context.request.http.headers
            ####################################################################
            # RELIABLE extraction of "x-env" header regardless of normalization
            ####################################################################
            xenv_val = v {
              xenv := lower(headers["x-env"])
              v := xenv
            } else = "" {
              # Header missing or undefined
              not headers["x-env"]
            }

            ####################################################################
            # Required header logic
            ####################################################################
            required_header := xenv_val == "dmz"
            
            ####################################################################
            # Query parsing helpers
            ####################################################################
            
            # Extract raw query string from path: "/api/v1/items?tenant=demo&region=emea"
            raw_query := split(path, "?")[1] {
              contains(path, "?")
            }
            
            # Build a map { "tenant": "demo", "region": "emea", ... }
            query := {k: v |
              raw_query                               # guard: only if query is present
              pair := split(raw_query, "&")[_]        # iterate "tenant=demo", "region=emea"
              kv := split(pair, "=")
              count(kv) == 2
              k := kv[0]
              v := kv[1]
            }
            
            ####################################################################
            # RELIABLE extraction of "tenant" param 
            ####################################################################
            tenant_val = v {
              v := query["tenant"]
              type_name(v) == "string"
            }

            # Tenant must be exactly "demo"
            tenant_demo {
              tenant_val == "demo"
              # for case-insensitive:
              # lower(tenant_val) == "demo"
            }

            ####################################################################
            # Authorization rules
            ####################################################################
            allow {
              required_header
              tenant_demo
              startswith(path, "/api/v1/items")
              method == "GET"
              roles[_] == "inventory.reader"
            }
            allow {
              required_header
              tenant_demo
              startswith(path, "/api/v1/items")
              method == "POST"
              roles[_] == "inventory.writer"
            }
            allow {
              required_header
              tenant_demo
              startswith(path, "/api/v1/items")
              method == "PUT"
              roles[_] == "inventory.writer"
            }
            allow {
              required_header
              tenant_demo
              startswith(path, "/api/v1/items")
              method == "DELETE"
              roles[_] == "inventory.deleter"
            }
            response := {
              "headers": {
                "X-Debug-Query-Raw": json.marshal(query),
                "X-Debug-Tenant-Val": tenant_val
              }
            } {
              allow
            }