apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: dmz-auth-inventory-policy
  namespace: app-global-dmz
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: inventory-route
    namespace: app-global-dmz
  rules:
    matches:
      - path:
          type: PathPrefix
          value: /
    authentication:
      keycloak:
        jwt:
          issuerUrl: https://auth.arencloud.com:30238/realms/rhcl-demo
          #jwksUrl: https://auth.arencloud.com:30238/realms/rhcl-demo/protocol/openid-connect/certs
          audiences:
            - rhcl-microservices
    authorization:
      opa-role-checks:
        opa:
          rego: |
            package kuadrant.authz
            roles := input.auth.identity.realm_access.roles
            path := input.context.request.http.path
            method := upper(input.context.request.http.method)
            headers := input.context.request.headers
            
            # Safely read header (avoids crash if missing)
            # Note: Headers are usually lower-cased keys in the map, 
            # and for single-value headers, the value is a string, not a list.
            xenv := "" {
              input.context.request.headers["x-env"]
              xenv := lower(input.context.request.headers["x-env"])
            } else {
              xenv := ""
            }
            allow = true
            
            #required_header {
            #  xenv == "dmz"
            #}
            #
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "GET"
            #  roles[_] == "inventory.reader"
            #}
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "POST"
            #  roles[_] == "inventory.writer"
            #}
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "PUT"
            #  roles[_] == "inventory.writer"
            #}
            #allow {
            #  required_header
            #  startswith(path, "/api/v1/items")
            #  method == "DELETE"
            #  roles[_] == "inventory.deleter"
            #}
            
            # -----------------------------
            # DEBUG OUTPUT (shows required_header)
            # -----------------------------
            response := {
              "headers": {
                # This prints whether `required_header` evaluated to true
                "X-Debug-Required-Header": required_header,

                # This prints what value x-env was read as
                "X-Debug-Xenv": xenv,

                # Useful extra context
                "X-Debug-Path": path,
                "X-Debug-Method": method,
              }
            }