apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wasm-plugin-pull-secret
  namespace: app-global-dmz
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: wasm-plugin-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .AUTH | b64dec }}'
  data:
    - secretKey: AUTH
      remoteRef:
        key: "wasm"
        property: AUTH