apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: inventories
  labels:
    app: inventory
    service: inventory
    version: v1
spec:
  selector:
    app: inventory
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: inventories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: "quay.io/rh-ee-egevorky/rhcl/inventory:0.1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: KEYCLOAK_ISSUER
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: KEYCLOAK_CLIENT_ID
            - name: INVENTORY_READ_ROLE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: INVENTORY_READ_ROLE
            - name: INVENTORY_WRITE_ROLE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: INVENTORY_WRITE_ROLE
            - name: INVENTORY_DELETE_ROLE
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: INVENTORY_DELETE_ROLE
            - name: INVENTORY_DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: INVENTORY_DB_URL
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
